# -*- coding: utf-8 -*-
"""Stegano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VjD9faVbJ8np2-F7cUo6KWGxJvGXq_Rq
"""

!pip install stegano

from stegano import lsb

secret = lsb.hide("kelinci.png", "halo saya farida, ini adalah pesan yang saya ingin sampaikan kepada kamu")
secret.save("kelinci.png")
#print(lsb.reveal("kelinci.png"))

from stegano import lsb

#secret = lsb.hide("kelinci.png", "halo saya leman, ini adalah pesan yang saya ingin sampaikan kepada kamu")
#secret.save("kelinci.png")
print(lsb.reveal("kelinci.png"))

"""# New Section"""